language: node_js
os: linux
services:
  - docker
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- docker pull vitr/casperjs
- docker run -d --name casperjs-daemon -v /home/ubuntu/tests:/ --restart always vitr/casperjs
- docker exec casperjs-daemon casperjs /home/casperjs-tests/index.js